### ISSUE TITLE
more glint toggles

### ISSUE THREAD

**Issue by Oguzhan5585** [jmb05/NoGlintyBooky#3]
toggles for deactivating the glint on tools & armor and those 4 other items as well would be nice :D i think that should cover all glints in the game

![image](https://user-images.githubusercontent.com/78051746/217596625-e88a71c3-3c48-4615-a9b2-f7204f0c9708.png)

**Comment by jmb05** [comment]
I will add an option for the lodestone compass aswell

**Comment by jmb05** [comment]
Added in 1.3.2
