### ISSUE TITLE
Crashes with quilt on 2.0

### ISSUE THREAD

**Issue by TheDinoKingK** [jmb05/NoGlintyBooky#4]
This wasn't an issue before but now it is for whatever reason
using qfapi 7.1.1 & qsl 6.1.1 along with Quilt loader 0.20.0 beta 11

![image](https://github.com/jmb05/LessGlintyThings/assets/45495320/25edc6bb-9969-4d49-b1b6-55f3a8470ed6)

**Comment by jmb05** [comment]
Fixed in Version 2.0.1
